### ISSUE TITLE
Using Sassport as simple dependency

### ISSUE THREAD

**Issue by ffoodd** [davidkpiano/sassport#16]
Hi there,

I'm currently using Sassport (through gulp-sassport) as a devDependency in a11y.css.

This works just fine and thanks to @HugoGiraudel and Sassport, I'm able to use a translation system in Sass \o/

But I'm now facing an issue I can't resolve for now: https://github.com/ffoodd/a11y.css/issues/297
Using Sassport's `require()` in my scss files is preventing a simple inclusion in other projects.

I tested using sassport as a simple dependency but due to itsnode- sass-wrapper nature, it won't work (or am I missing something?).

For now I'm wondering if a `prepare` script in my own project would do the trick, but I'm not sure how to do this: it would need sassport to write sass files (something like: replacing the `require() by what it's requiring and output new scss files to use as dependencies).

I'm probably wrong with this (not really my specialty) so I'm asking four your opinion :)

**Comment by davidkpiano** [comment]
Not sure how to help here - if you want to include JSON files into your Sass files, you have to have some sort of adaptor, which includes doing everything that Sassport requires.

**Comment by ffoodd** [comment]
You're right, I was just wondering if any idea could come up. I'm closing this and will try another way.

Thanks for reading!
