### ISSUE TITLE
Allow 'index' Sass/SCSS files to be automatically imported

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/sassport#3]
This is a highly requested (and planned) feature in Sass: https://github.com/sass/sass/issues/690

The logic will be (for `@import 'foo/bar'`):
- If registered as a Sassport export, import the designated file/directory mapped to `foo/bar`.
- If module doesn't exist, search **load-paths** (planned Sassport feature) for directory.
  - e.g. `node_modules/foo/bar`
- If `bar.scss, _bar.scss, bar.sass, _bar.sass` exists, import that.
- Else, if `/bar` is a directory, import (in this priority order) `index.scss, index.sass, _index.scss, _index.sass`

Example:
```scss
// imports node_modules/sassdash/_index.scss
@import 'sassdash';

// imports path/to/foo-module/bar/index.scss, given
// 'foo-module' is registered as a Sassport module
@import 'foo-module/bar';
```

**Comment by ArmorDarks** [comment]
That would be nice!

Shouldn't `index.scss` and `index.sass` go last?

I'm not sure that someone would like to import file, which also compiles into standalone css.

**Comment by davidkpiano** [comment]
@ArmorDarks This feature has landed! :boom: If you want to take a look at the details, [peek into the file](https://github.com/davidkpiano/sassport/blob/master/src/utils/resolve.js) responsible for resolving paths.

You might be right; I'm doing it based on absolute path first - if that exists, it should grab that. If this becomes an issue later (with unexpected index files being compiled instead of their partial counterparts) we can revisit this issue.

**Comment by dkebler** [comment]
Trying to use sassport to process _index.scss files

I am using gulp-sassport in place of gulp-sass with this code below and but it apparently doesn't find the "includePaths" for node-sass.    I'm not using any sassport modules so I just passed in an empty array.  Is that the correct way to handle no modules?

When it comes to _index.scss gulp-sassport is working but it is either not passing on my includePaths to node-sass or worse sassport is messing up resolving my bower library file paths which is what I am passing to node-sass via the csass.paths array.

```
// var process_sass = require('gulp-sass');  //uses node-sass
var process_sass = require('gulp-sassport');  //uses node-sass

var done = new Promise( function(resolve,reject){
  gulp.src(csass.src,csass.paths)
      .pipe(plumber({errorHandler: onError})) // not needed for gulp 4.0 and above
      .pipe(gulpif(Config.buildType === 'dev',sourcemaps.init()))
      .pipe(process_sass([],{includePaths: csass.paths})).on('end', function(){ Debug('Libsass done...'); })
...
```

**Comment by davidkpiano** [comment]
Hey @dkebler this is probably a bug with an easy fix. I'll have a solution for you shortly.

**Comment by dkebler** [comment]
if you need more input look at my repo from which that code comes....  /lib/sass.js

https://github.com/dkebler/super-static-site-starter#bower-for-the-browser
https://github.com/dkebler/super-static-site-starter/blob/master/lib/sass.js

**Comment by davidkpiano** [comment]
@dkebler as far as the actual importing of `includedPaths`, that is already included in Sassport and seems to be working fine. I added a unit test just to make sure: https://github.com/davidkpiano/sassport/commit/85292b34f932c7f0cbc3e936f0cba5e0e658338a#diff-807474f2f73449feb7997c92874b6223R59

I'll check to see if `gulp-sassport` has the latest version and has the same issue that you're talking about.

**Comment by dkebler** [comment]
─┬ gulp-sassport@0.4.0
  └── sassport@0.8.0 

updated, even deleted node-modules and reinstalled.

Nope, still no go.  I wrote a simplified version of my sass.lib, still no go

gulp-sass fine works, gulp-sassport no.  Here is code, below is output

Any way to get gulp-sassport,sassport to log to console or file options it is passing to node-sass? It just seems my array of paths is not getting to node-sass as per the options.error shown in the terminal (below) for node-sass.

Your test is not apparently testing the exact same use case.  How about more than one path in your array of paths? like mine use case.  Take out compressed option?

```
gulp.task('sass', function() {

  // PRECCOMPILE - SASS-SCSS
  /* jshint node:true */

var gulp         = require('gulp');
var process_sass = require('gulp-sassport');  //uses node-sass
// var process_sass = require('gulp-sass');  //uses node-sass


  // config files
  var bower = require('./config/sass-bower.json');
  var dest = './';
  var src = './assets/styles/sass/site.scss';
  Info('Sass source: ', Config.buildType, ', output to: ',src);
  Info('Sass dest: ', Config.buildType, ', output to: ',dest);
  Info('Bower Sass Library Paths \n', bower.paths);

 var done = new Promise( function(resolve,reject){
    gulp.src(src,bower.paths)
        .pipe(process_sass([],{includePaths: bower.paths})).on('end', function(){ Debug('Libsass done...'); })
          .pipe(gulp.dest(dest))
                 .on('end', resolve )
           ;  //end of stream

  }); //end of Promise

return done;  // return the promise

});
```
```
terminal output

  Info Sass source:  +0ms dev , output to:  ./assets/styles/sass/site.scss
  Info Sass dest:  +0ms dev , output to:  ./
  Info Bower Sass Library Paths 
 +0ms [ 'bower_components/modular-scale/stylesheets',
  'bower_components/scss-blend-modes/stylesheets',
  'bower_components/color-schemer/stylesheets',
  'bower_components/sass-flex-mixin',
  'bower_components/sassy-maps/sass',
  'bower_components/compass-breakpoint/stylesheets',
  'bower_components/sass-mediaqueries',
  'bower_components/sass-mq',
  'bower_components/bemify/sass',
  'bower_components/support-for/sass',
  'bower_components/normalize-scss/sass',
  'bower_components/breakpoint-slicer/stylesheets' ]

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: assets/styles/sass/vendors/_packages.scss
Error: File to import not found or unreadable: /mnt/AllData/hacking/Super-Static-Site-Starter/assets/styles/sass/vendors/sassy-maps
       Parent style sheet: /mnt/AllData/hacking/Super-Static-Site-Starter/assets/styles/sass/vendors/_packages.scss
        on line 4 of assets/styles/sass/vendors/_packages.scss
>> @import 'sassy-maps';
    at options.error (/mnt/AllData/hacking/Super-Static-Site-Starter/node_modules/node-sass/lib/index.js:277:32
```
sass
https://github.com/dkebler/super-static-site-starter/blob/master/assets/styles/sass/site.scsss

https://github.com/dkebler/super-static-site-starter/blob/master/assets/styles/sass/vendors/_packages.scss

**Comment by davidkpiano** [comment]
@dkebler I added more paths here: https://github.com/davidkpiano/sassport/commit/88a88a543d9d8e52c9fcab35591e40d80e40f662

Can you please provide me a fully functional, executable test case [gist](https://gist.github.com) so I can more easily see what the issue is? `includePaths` should work the _exact_ same way as in `gulp-sass`.

**Comment by dkebler** [comment]
just now getting back to this.

rather than a gist I made this easier to reproduce by stripping out this issue from my project into its own repo.

https://github.com/dkebler/sassport-test.git

So just clone and install/run per the readme.md

I still get the gulp-sass version compiles fine importing all the sass files in bower libraries but gulp-sassport fails. `(see ./scss/vendors/_packages.scss)`

```
Error: scss/vendors/_packages.scss
Error: File to import not found or unreadable: /mnt/AllData/hacking/sassport/scss/vendors/sassy-maps
       Parent style sheet: /mnt/AllData/hacking/sassport/scss/vendors/_packages.scss
        on line 4 of scss/vendors/_packages.scss
>> @import 'sassy-maps';
```

You can uncomment this line   //console.log('Bower Sass Library Paths \n', bower.paths);  if you want to see the paths being passed to node-sass with "includepaths".

btw I am running both latest node 5 and npm 3 on linux ubuntu 14.04

**Comment by davidkpiano** [comment]
@dkebler can you post this as a separate issue? I'll be able to keep track of it better 😊

**Comment by zivc** [comment]
So lads, two years later.. redundant issue?
