### ISSUE TITLE
Event on import

### ISSUE THREAD

**Issue by IngwiePhoenix** [davidkpiano/sassport#8]
https://github.com/IngwiePhoenix/sassport-loader/issues/1
/cc @stevoland

A user of my SassPort loader is trying to make WebPack recognize changes beyond their SCSS file. Usually, Webpack will pick up all the files that it encoutnered through `require`, or when it's importer was invoked.

however, the require statements used inside Sassport processed SCSS files uses a special mechanism.

I am looking for some kind of event or hook that I can add the following bit of code to:

```javascript
function onRequireFile(file) {
    loaderCtx.addDependency(file);
}
```

This is another way of telling WebPack "hey, mind this file too!".

Please let me know how to do this, thanks!

**Comment by davidkpiano** [comment]
Most likely, we can look at this line to see what we can do for a hook: https://github.com/davidkpiano/sassport/blob/master/src/index.js#L204

I'm thinking that we can add an `onRequire` or a `requireCallback` as an option for a Sassport module:

```js
sassport([...], {
  onRequire: function(filePath, done) {
    // Do any Webpack related stuff...
    loaderCtx.addDependency(filePath);

    // either return the result object...
    return require(filePath);

    // or do it asyncronously with done()
    done(require(filePath));
  }
})
```

Would that be a good solution? That would allow the developer to customize what happens when a file is `require()`'d inside Sass files.

**Comment by IngwiePhoenix** [comment]
That would work just fine indeed! (:

**Comment by davidkpiano** [comment]
@IngwiePhoenix Here's the unit test for the requested feature: https://github.com/davidkpiano/sassport/commit/e9a20481536fa4673fa46887667503e3592e6b35

For this commit: https://github.com/davidkpiano/sassport/commit/7d96578d4a10c3d262c36a5a202758b1c0f7f3a9

I'll have to revisit async `onRequire` a different time, but this should be satisfactory for now.

Can you test this on your end and see if it works for the Webpack use-case? Then, I'll bump the version on NPM.

Thanks! :smile:

**Comment by IngwiePhoenix** [comment]
Cool! Thanks for that :)
I will run the test later today and see if WebPack responds properly to it.
